services:
  # Base de datos PostgreSQL
  - type: postgres
    name: practicas-db
    databaseName: practicas_db
    user: practicas_user
    plan: free
    region: oregon

  # Servicio Web (Django)
  - type: web
    name: practicas-web
    runtime: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        fromDatabase:
          name: practicas-db
          property: connectionString
